version: "3.9"

services:
  loader:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WEAVIATE_HOST=host.docker.internal  # si estás en Windows o Mac, para conectar a localhost del host
      - WEAVIATE_PORT=8080
